### ISSUE TITLE
data-action with drag and drop events

### ISSUE THREAD

**Issue by etdsoft** [stimulusjs/stimulus#127]
Hi there,

I have the following HTML

```html
<ul
    class="list-cards"
    data-target="dragdrop.dropzone"
    data-action="click->dragdrop#moveCard">
```

Which works as expected and ends up calling `moveCard()` in the controller.

However, if I change the `data-action` to the event I really want to handle (`drop`), the method in the controller never gets called:

```html
<ul
    class="list-cards"
    data-target="dragdrop.dropzone"
    data-action="drop->dragdrop#moveCard">
```

It seems that drag and drop events are [using the DOM event model](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#Drag_Events), and should be picked up by Stimulus, but I'm not 100% sure.

What am I missing?

Thanks!

**Comment by sstephenson** [comment]
This is a quirk of the HTML Drag and Drop API. In order to receive a `drop` event, you first have to observe either `dragenter` or `dragover` and call `event.preventDefault()`.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations#drop):

> When the user releases the mouse, the drag and drop operation ends. If the mouse was released over an element that is a valid drop target, that is, one that cancelled the last `dragenter` or `dragover` event, and then the drop will be successful, and a `drop` event will fire at the target. Otherwise, the drag operation is cancelled, and no `drop` event is fired.

**Comment by pulgamecanica** [comment]
I tried this but didn't fix it... :( Any other suggestions?
dragenter & dragover are not called either.
I know I have everything well setup, because if I use "click" or "change" my controller function DOES get's called, but seams like drag or dragenter or dragover are never called.
I tried to "preventDefault()" "on change" but the drop still doesn't work :(

**Comment by pulgamecanica** [comment]
Alright I fixed it..... I'll leave what I did to fix it for other sould wandering here:

> On the Stimulus controller I call this function on **"dragover"**

```
dragover(event) {
    event.preventDefault()
    return true
}
```

Seams like I had to return true for it to work.... doesn't work without it....

**Comment by seans84** [comment]
Old thread, but the answer is a little more nuanced and I wanted to add clarity.

The event needs to be cancelled (`event.preventDefault()`) on `dragover` in order to allow a `drop` event to fire.

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations#performing_a_drop

> If the mouse is released over an element that is a valid drop target, that is, one that cancelled the last [dragenter](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragenter_event) or [dragover](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragover_event) event, then the drop will be successful, and a [drop](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event) event will fire at the target. Otherwise, the drag operation is cancelled, and no [drop](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event) event is fired.

And from https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragover_event
```
target.addEventListener("dragover", (event) => {
  // prevent default to allow drop
  event.preventDefault();
});
```

When this is done then you can add something like this

```
<div
  data-controller="dropzone"
  data-action="dragover->dropzone#activate drop->dropzone#drop"
></div>

drop(event) {
  event.preventDefault();
  // Do something here
}

activate(event) {
  event.preventDefault();
}
```

**Comment by pulgamecanica** [comment]
It makes sense now haha!
