### ISSUE TITLE
Clarify usage of pre-made widget

### ISSUE THREAD

**Issue by benzen** [stimulusjs/stimulus#140]
This project is very interesing.
Still the documentation is unclear in one point.

In the building something real, I think there should be a section that talk about integration with a pre-made widget, maybe some jquery stuff.

Any of use will be confronted to this kind of problem in the real world.

Thanks a lot for you efforts

**Comment by javan** [comment]
Thanks for the feedback! I don't think we could talk about that in a general enough way since every 3rd-party widget is different. Our community forum is a great place such discussions though. For example:
- https://discourse.stimulusjs.org/t/how-to-use-stimulus-inside-bootstraps-popovers/177
- https://discourse.stimulusjs.org/t/call-stimulus-function-from-google-maps-callback/191
