### ISSUE TITLE
Wait for controllers to initialize

### ISSUE THREAD

**Issue by incompletude** [stimulusjs/stimulus#201]
Loving it so far, good job. Sorry if this is not the right place for this question.

---

In my `navigation controller` I'm trying to use `this.application.getControllerForElementAndIdentifier` during **initialize** (can't move to click, third party) to obtain controllers that contains behavior I need to attach to my the navigation solution (close stuff, hide stuff, etc), but (I think) because the navigation occurs first in the HTML, during its initialize, other controllers still don't exist, so I can't get an instance of them.

`stimulus` is in a constant state of connecting and disconnecting (which is very nice), and I think it doesn't emit any kind of everything ready (but this for first load would be very useful I think).

What is the proper way to approach this problem?

**Comment by incompletude** [comment]
Perfect. It solves the problem.

Why not have an API to that? Like `application.tick()` or something?

**Comment by sstephenson** [comment]
This has come up a few times before (#35, #183).

> Why not an API to that? Like `application.tick()` or something?

It's the wrong level of abstraction for Stimulus. You shouldn't have to know about the microtask queue or JavaScript event loop in order to link two controllers together. Nor should you have to call the `getControllerForElementAndIdentifier` method (which has an intentionally long-winded name to discourage its use).

What we want is a way to declaratively link two controllers together in HTML, plus some sort of callback that's invoked when the link is established and both controllers are initialized.

We would love to hear any proposals for such an API! Otherwise, discussion for how to work with the existing API is best suited for the [community forum](https://discourse.stimulusjs.org).

Thank you for opening the issue!
