### ISSUE TITLE
Datamap this.data.get(key) should return undefined

### ISSUE THREAD

**Issue by ngan** [stimulusjs/stimulus#203]
Datamap's `this.data.get(key)` method returns `null` for data attributes that are not defined. I use TypeScript and find myself doing a lot of checks/casting when comparing something against values returned from that method. Javascript [`Element.dataset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) getter methods return `undefined`, and it feels more correct that an undefined data attribute's value is `undefined` since, well, it's undefined.

**Comment by ngan** [comment]
On second thought, `null` [seems](https://stackoverflow.com/questions/37980559/is-it-better-to-return-undefined-or-null-from-a-javascript-function) to be the more correct return value.

**Comment by sstephenson** [comment]
To follow up, `DataMap#get(key)` returns `string | null` because that's the return type of [`Element#getAttribute(name)`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute). I agree that `string | undefined` would be the appropriate type if the Data Map API exposed getter properties instead of a `get(key)` method.

The [proposed Values API](#202) avoids this problem entirely: when their underlying attributes are missing, value properties return their type's default value.
