### ISSUE TITLE
Register controller via dynamic import

### ISSUE THREAD

**Issue by kristoforsalmin** [stimulusjs/stimulus#261]
Hi,

I was wondering if it's possible to use dynamic import to register a controller? Here's an example:

```js
// main.js
const application = Application.start();

application.register('hello', () => import('./hello_controller.js'));

// hello_controller.js
class HelloController extends Controller {
  static get targets() {
    return ['name'];
  }
}
```

If `<div data-controller="hello">` is present, then `hello_controller.js` will be fetched and registered 🙂

Thanks!

**Comment by javan** [comment]
The above won't work because `Application#register` expects a controller as the second argument (not a function or promise): https://github.com/stimulusjs/stimulus/blob/0856b1dfc1114ad6e4d524657806451323fbe1da/packages/%40stimulus/core/src/application.ts#L38-L40

You *can* load and register controllers asynchronously:
```js
const application = Application.start();
import('./hello_controller.js').then(module => {
  application.register('hello', module.default)
})
```
…but that won't happen automatically when a `<div data-controller="hello">` appears. You'd need to orchestrate it yourself.

**Comment by kristoforsalmin** [comment]
@javan thanks for the reply 🙂

**Comment by woto** [comment]
There is an interesting js package which dynamically loads controllers https://github.com/danieldiekmeier/stimulus-controller-resolver

But be aware, i found the problems with CI which still can't overcome
https://github.com/danieldiekmeier/stimulus-controller-resolver/issues/9
