### ISSUE TITLE
hashchange is not caught

### ISSUE THREAD

**Issue by traskat** [stimulusjs/stimulus#297]
hello,

i have the problem that the event onhashchange isn't fired
`<div class="test" data-controller="general" data-action="hashchange->general#test"></div>`
that is my first div after the body tag.
here is the controller:
`
application.register("general", class extends stimulus.Controller {
		test(event) {
			console.log("test", this, this.arguments)
		}
})
`

but the function never gets called
The URL will change when i click a link a child controller

thanks in advance

**Comment by javan** [comment]
The [`hashchange` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event) is fired at `window` so you need to listen for it there instead of on your controller's element. Stimulus supports that with a special [*Global Events*](https://stimulusjs.org/reference/actions#global-events) syntax:
```html
<div data-controller="general"
     data-action="hashchange@window->general#test">
  …
</div>
```
