### ISSUE TITLE
EventListenerObject location?

### ISSUE THREAD

**Issue by nhrones** [stimulusjs/stimulus#91]
Where in Action.ts ...
export class Action implements EventListenerObject 
It is unclear where this interface is declared. it is not imported in the class file?

**Comment by javan** [comment]
That's a lesser-known part of the [standard DOM interface](https://dom.spec.whatwg.org/#interface-eventtarget) so it's [provided automatically by TypeScript](https://github.com/Microsoft/TypeScript/blob/8b81d19b6db9267da5fa1fda8f7640cbac517c65/lib/lib.d.ts#L18468-L18470). Here's a great introduction: https://medium.com/@WebReflection/dom-handleevent-a-cross-platform-standard-since-year-2000-5bf17287fd38

**Comment by javan** [comment]
For any future readers, here's the implementation:
https://github.com/stimulusjs/stimulus/blob/4db9f6b3e7900686fd3d03c0997dea3b8ce5fa05/packages/%40stimulus/core/src/action.ts#L6 https://github.com/stimulusjs/stimulus/blob/4db9f6b3e7900686fd3d03c0997dea3b8ce5fa05/packages/%40stimulus/core/src/action.ts#L29-L33

h/t @WebReflection

**Comment by nhrones** [comment]
Thanks for this. Great to know.
